const sb=supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);const $=id=>document.getElementById(id);let products=[],editing=null;const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function start(){if(SUPABASE_URL.startsWith("PASTE_")){ $("loginMsg").textContent="Add your Supabase URL and publishable key to config.js first.";return }const {data:{session}}=await sb.auth.getSession();session?openDashboard():showLogin()}
function showLogin(){$("loginPanel").hidden=false;$('dashboard').hidden=true}
async function openDashboard(){const {data:{user}}=await sb.auth.getUser();$('userArea').innerHTML=`<span style="font-size:12px">${esc(user.email)}</span> <button id="logout" style="margin-left:10px;padding:7px">Logout</button>`;$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()};$('loginPanel').hidden=true;$('dashboard').hidden=false;await load()}
async function login(){const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){$('loginMsg').textContent=error.message;return}openDashboard()}
$('loginBtn').onclick=login;$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});
async function load(){const {data,error}=await sb.from('products').select('*').order('created_at',{ascending:false});if(error){$('productTable').innerHTML=`<p class="msg">${esc(error.message)}</p>`;return}products=data||[];render()}
function render(){const q=$('adminSearch').value.toLowerCase(),selected=$('adminFilter').value,cats=[...new Set(products.map(p=>p.category).filter(Boolean))];$('adminFilter').innerHTML='<option>All</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join('');$('adminFilter').value=selected;let list=products.filter(p=>(selected==='All'||p.category===selected)&&(!q||[p.name,p.brand,p.category].join(' ').toLowerCase().includes(q)));$('stats').innerHTML=`<div class="stat"><b>${products.length}</b><small>Total products</small></div><div class="stat"><b>${products.filter(p=>p.published).length}</b><small>Published</small></div><div class="stat"><b>${products.filter(p=>p.featured).length}</b><small>Featured</small></div>`;$('productTable').innerHTML=list.map(p=>`<div class="row"><div><b>${esc(p.name)}</b><small>${esc(p.brand||'')} · ${esc(p.category||'')}</small></div><div><b>${money(p.price)}</b><small>${p.rating||0} ★</small></div><div><span class="tag">${esc(p.badge||'STANDARD')}</span><small class="${p.published?'status':''}">${p.published?'Published':'Hidden'}</small></div><div class="actions"><button data-edit="${p.id}">Edit</button> <button data-toggle="${p.id}">${p.published?'Hide':'Publish'}</button> <button class="danger" data-delete="${p.id}">Delete</button></div></div>`).join('')||'<p>No products.</p>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>toggle(b.dataset.toggle));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeProduct(b.dataset.delete))}
function reset(){editing=null;$('editorTitle').textContent='Add product';['pid','name','brand','category','price','rating','reviews','badge','image_url','description','specs'].forEach(k=>$(k).value='');$('published').checked=true;$('featured').checked=false;$('saveMsg').textContent=''}
function add(){$('editor').hidden=false;reset()}function edit(id){const p=products.find(x=>String(x.id)===String(id));editing=p;$('editorTitle').textContent='Edit product';$('pid').value=p.id;['name','brand','category','price','rating','reviews','badge','image_url','description'].forEach(k=>$(k).value=p[k]??'');$('specs').value=(p.specs||[]).join('\n');$('published').checked=!!p.published;$('featured').checked=!!p.featured;$('saveMsg').textContent='';$('editor').hidden=false}
$('addBtn').onclick=add;$('closeEditor').onclick=$('cancelBtn').onclick=()=>$('editor').hidden=true;
async function save(){const row={name:$('name').value.trim(),brand:$('brand').value.trim(),category:$('category').value.trim(),price:Number($('price').value||0),rating:Number($('rating').value||0),reviews:Number($('reviews').value||0),badge:$('badge').value,image_url:$('image_url').value.trim(),description:$('description').value.trim(),specs:$('specs').value.split('\n').map(s=>s.trim()).filter(Boolean),published:$('published').checked,featured:$('featured').checked};let r=editing?await sb.from('products').update(row).eq('id',editing.id):await sb.from('products').insert(row);if(r.error){$('saveMsg').textContent=r.error.message;return}$('editor').hidden=true;await load()}
$('saveBtn').onclick=save;$('adminSearch').oninput=render;$('adminFilter').onchange=render;
async function toggle(id){const p=products.find(x=>String(x.id)===String(id));const r=await sb.from('products').update({published:!p.published}).eq('id',id);if(r.error)alert(r.error.message);await load()}
async function removeProduct(id){if(!confirm('Delete this product?'))return;const r=await sb.from('products').delete().eq('id',id);if(r.error)alert(r.error.message);await load()}
start();