-- UNBOX_GADGS SUPABASE SETUP
-- 1. In Supabase Authentication -> Users, create your admin user.
-- 2. Copy that user's UUID.
-- 3. Replace YOUR_ADMIN_USER_UUID below, then run this SQL in SQL Editor.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text,
  category text not null,
  price numeric(12,2) not null default 0,
  image_url text,
  badge text,
  rating numeric(2,1) default 0,
  reviews integer default 0,
  description text,
  specs jsonb not null default '[]'::jsonb,
  published boolean not null default true,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

alter table public.products enable row level security;
alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean language sql security definer set search_path = public as $$
  select exists (select 1 from public.admin_users where user_id = auth.uid());
$$;

drop policy if exists "public read published products" on public.products;
create policy "public read published products" on public.products
for select to anon, authenticated using (published = true or public.is_admin());

drop policy if exists "admins insert products" on public.products;
create policy "admins insert products" on public.products
for insert to authenticated with check (public.is_admin());

drop policy if exists "admins update products" on public.products;
create policy "admins update products" on public.products
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins delete products" on public.products;
create policy "admins delete products" on public.products
for delete to authenticated using (public.is_admin());

drop policy if exists "admins read admin_users" on public.admin_users;
create policy "admins read admin_users" on public.admin_users
for select to authenticated using (public.is_admin());

insert into public.admin_users(user_id)
values ('YOUR_ADMIN_USER_UUID')
on conflict do nothing;

-- Optional sample product. Delete if you want an empty catalogue.
insert into public.products(name,brand,category,price,badge,rating,reviews,description,specs,published,featured)
values ('Sample Product','UNBOX_GADGS','Accessories',999,'NEW',5,0,'Replace this sample with your own product.','["Add your first specification","Add another specification"]'::jsonb,true,true);
